In [4]:
from unicirc import sample_from_group

group = "SO"

n_targets = 10
seed = 69214

n = 3
targets = sample_from_group(n, n_targets, group, seed)
working = [0, 2, 3, 6, 7, 8, 9]
not_working = [1, 4, 5]

In [5]:
targets[1]

array([[ 0.05556411, -0.16449773,  0.82617651,  0.22181269,  0.13749852,
        -0.42615365, -0.17077924,  0.09168593],
       [-0.15547675, -0.15574738, -0.46810346,  0.41905734, -0.1786796 ,
        -0.69774437,  0.07346989,  0.18074404],
       [-0.23415549, -0.3781924 , -0.01828083, -0.55962693, -0.39789658,
        -0.19892451, -0.48147646, -0.24272   ],
       [-0.78145738, -0.01074722,  0.2454324 ,  0.20361729, -0.35515275,
         0.27690485,  0.27771051,  0.08705689],
       [ 0.18143706, -0.2795774 , -0.02145222,  0.56023785, -0.17265922,
         0.22499146, -0.12009587, -0.69262908],
       [-0.13987797,  0.84356709,  0.03460821,  0.0814809 , -0.14461846,
        -0.20388306, -0.34429424, -0.28279061],
       [ 0.41718524,  0.12444539,  0.18986513, -0.19302355, -0.62560023,
        -0.17106047,  0.55389597, -0.09861484],
       [-0.28408874, -0.01681209,  0.00579518, -0.25056755,  0.47181697,
        -0.30634534,  0.46554443, -0.56833346]])

In [8]:
import numpy as np
# Special orthogonal group:
# Real-valued
assert targets.dtype == np.float64
# transpose is inverse
assert all(np.allclose(t.T @ t, np.eye(2**n)) for t in targets)
# Determinant is one
assert np.allclose(np.linalg.det(targets), 1)

In [18]:
import scipy as sp

first_working = targets[working[0]]
gen_working = sp.linalg.logm(first_working)

first_non_working = targets[not_working[0]]
gen_non_working = sp.linalg.logm(first_non_working)

print(np.round(gen_working, 2))

print(np.round(gen_non_working, 2))
assert np.allclose(gen_working.T, -gen_working)
assert np.allclose(gen_non_working.T, -gen_non_working)
print(np.linalg.norm(gen_working))
print(np.linalg.norm(gen_non_working))

[[ 0.    0.23 -0.05  0.07  0.86 -0.86 -0.74  0.45]
 [-0.23 -0.    0.64 -0.17  0.68  0.25  1.06 -0.65]
 [ 0.05 -0.64 -0.    0.41 -1.1   0.35  0.03  0.86]
 [-0.07  0.17 -0.41 -0.    0.3  -1.35 -0.   -0.53]
 [-0.86 -0.68  1.1  -0.3  -0.   -0.47  0.03 -1.  ]
 [ 0.86 -0.25 -0.35  1.35  0.47 -0.    0.99  0.41]
 [ 0.74 -1.06 -0.03  0.   -0.03 -0.99 -0.    0.41]
 [-0.45  0.65 -0.86  0.53  1.   -0.41 -0.41 -0.  ]]
[[-0.    0.23  1.07  0.82  0.12 -0.18 -0.36  0.77]
 [-0.23  0.   -0.14  0.4   0.01 -1.72 -0.2  -0.41]
 [-1.07  0.14 -0.   -0.7  -0.27 -0.68 -0.38 -0.84]
 [-0.82 -0.4   0.7  -0.   -0.56  0.27  0.29  0.48]
 [-0.12 -0.01  0.27  0.56 -0.   -0.12  0.45 -1.7 ]
 [ 0.18  1.72  0.68 -0.27  0.12 -0.   -0.09  0.  ]
 [ 0.36  0.2   0.38 -0.29 -0.45  0.09 -0.   -0.76]
 [-0.77  0.41  0.84 -0.48  1.7  -0.    0.76  0.  ]]
4.858084273851788
4.955366444418875


In [25]:
from unicirc import matrix_v2

mat_fn = matrix_v2(n, "SO")
dim = (2**n * (2**n - 1)) // 2
for _ in range(100):
    params = np.random.normal(size=dim) * 0.2
    mat = mat_fn(params)
    assert mat.dtype == np.float64, f"{mat.dtype=}"
    assert np.allclose(mat @ mat.T, np.eye(2**n))
    assert np.isclose(np.linalg.det(mat), 1)

In [26]:
from unicirc import make_ansatz
import pennylane as qml
ansatz = make_ansatz(n, "SO")
print(qml.draw(ansatz)(params))


0: ──RY(-0.03)─╭●──RY(0.10)────────────────╭●──RY(0.26)───────────────╭●──RY(0.03)──── ···
1: ──RY(0.10)──╰Z──RY(-0.37)─╭●──RY(0.19)──╰Z──RY(0.05)─╭●──RY(-0.10)─╰Z──RY(-0.12)─╭● ···
2: ──RY(-0.18)───────────────╰Z──RY(-0.04)──────────────╰Z──RY(0.08)────────────────╰Z ···

0: ··· ────────────╭●──RY(0.31)────────────────╭●──RY(0.11)────────────────╭●──RY(0.02)─── ···
1: ··· ──RY(-0.20)─╰Z──RY(-0.10)─╭●──RY(-0.16)─╰Z──RY(-0.39)─╭●──RY(0.56)──╰Z──RY(0.02)─╭● ···
2: ··· ──RY(-0.08)───────────────╰Z──RY(0.09)────────────────╰Z──RY(-0.12)──────────────╰Z ···

0: ··· ───────────╭●──RY(0.06)─┤  
1: ··· ──RY(0.02)─╰Z───────────┤  
2: ··· ──RY(0.23)──────────────┤  
